package ru.itsjava.exceptions;

public class ExceptionPractice {
    public static void main(String[] args) {
        // throw new RuntimeException("m");
      /*  try {
            throw new Exception();
        } catch (Exception e) {
            System.out.println("!!!");
            //e.printStackTrace();
        }*/
       /* try {
            System.out.println("Begin");
         //   throw new Exception();
        } catch (Exception e) {
            System.out.println("!!!");
            //e.printStackTrace();
        }finally {
            System.out.println("Finally");
        }
        System.out.println("end");*/

      /*  try {
            throw new RuntimeException();
        } catch (RuntimeException runtimeException) {
            System.out.println("runtime");
        } catch (Throwable throwable) {
            System.out.println("throwable");
        }*/
       /* Calculator calculator = new Calculator();
        System.out.println("calculator.division(5,0) = " + calculator.division(5, 0));*/
    }
}
